/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trabalho.junit.gradle;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, NoSuchFieldException {
        System.out.println(new App().getGreeting());
        Object arquivoFromReflection = null;
		try {
			arquivoFromReflection = Class.forName("negocio.Date").getDeclaredConstructor().newInstance();            
		} catch (InstantiationException e) {			
			e.printStackTrace();
		} catch (IllegalAccessException e) {			
			e.printStackTrace();
		} catch (ClassNotFoundException e) {			
			e.printStackTrace();
		}        
        arquivoFromReflection.getClass().getDeclaredFields();  
        arquivoFromReflection.getClass().getDeclaredConstructor().newInstance();
        Field dayField = arquivoFromReflection.getClass().getDeclaredField("day");      
        byte day = 26;
        dayField.setByte(arquivoFromReflection, day);
    }
}
